---
- name: make Arch comfy
  hosts: localhost

  tasks:
    - name: install core utilities
      become: true
      community.general.pacman:
        name: base-devel git go
        state: present

    - name: install UI packages
      become: true
      ignore_errors: true
      community.general.pacman:
        name: sway xorg-xwayland waylock waybar noto-fonts-emoji noto-fonts-emoji pulseaudio otf-font-awesome ttf-croscore mako ttf-dejavu ttf-liberation noto-fonts
        state: present

    - name: install essential tools
      become: true
      ignore_errors: true
      community.general.pacman:
        name: alacritty firefox playerctl
        state: present

    - name: install utilities
      become: true
      community.general.pacman:
        name: virtualbox cups
        state: present

    - name: clone Yay
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: ~/yay

    - name: install Yay
      ansible.builtin.command:
        chdir: ~/yay
        cmd: makepkg -si --noconfirm

    - name: enable CUPS
      ansible.builtin.systemd:
        enabled: yes
        name: cups.service

