---
- name: make Arch comfy
  hosts: localhost

  tasks:
    - name: install core utilities
      become: true
      community.general.pacman:
        name: base-devel git go
        state: present

    - name: clone Yay
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: ~/yay

    - name: install Yay
      ansible.builtin.command:
        chdir: ~/yay
        cmd: makepkg -si

    - name: install UI packages
      become: true
      community.general.pacman:
        name: alacritty firefox noto-fonts-emoji noto-fonts-emoji sway pulseaudio otf-font-awesome ttf-croscore cups playerctl
        state: present

    - name: install tools
      become: true
      community.general.pacman:
        name: virtualbox cups
        state: present

