---
- name: update web servers
  hosts: all
  remote_user: root

  tasks:
    - name: install UI packages
        community.general.pacman:
          name: alacritty firefox noto-fonts-emoji noto-fonts-emoji sway pulseaudio otf-font-awesome ttf-croscore cups playerctl
          state: present

    - name: install tools
        community.general.pacman:
          name: virtualbox cups
          state: present